### ISSUE TITLE
Error message when quitting the check window with

### ISSUE THREAD

**Issue by languitar** [rhysd/vim-grammarous#53] opened 2017-12-20 13:07 UTC
When I close the checking window with `q`, I always see the following error message:

```
Error detected while processing function grammarous#info_win#action_quit:
line    3:
E108: No such variable: "b:grammarous_preview_bufnr"
```

**Comment by rhysd** [comment] 2017-12-21 02:28
Could you provide more information about your environment to reproduce problem? At least it does not reproduce in my local.

- Vim version (i.e. 7.4.x or 8.0.x or Neovim 2.x or ...)
- Your OS

**Comment by rhysd** [comment] 2017-12-21 02:52
I improved to close preview window. Could you try out the latest?

**Comment by languitar** [comment] 2017-12-21 09:11
This is gone with the update. :)  I am running neovim 0.2.2 on Linux.

**Comment by rhysd** [comment] 2017-12-21 09:44
Yes. Thank you for confirming. I’m closing this.

**Comment by languitar** [comment] 2017-12-21 09:44
Is there any way to actually return to the correct buffer afterwards?

**Closed by rhysd** 2017-12-21 09:44 UTC

**Comment by rhysd** [comment] 2017-12-21 10:33
Currently there is no way to do that. 'quit' action only `:quit` the window with cleanup.

**Comment by languitar** [comment] 2017-12-21 11:43
I think I once had a discussion on how to achieve this reliably in vimtex in this issue: https://github.com/lervag/vimtex/issues/637 Maybe you could adapt the solution there?

**Comment by rhysd** [comment] 2017-12-21 12:34
Actually I can implement it easily. Not understanding it's practically useful or not (because I'm satisfied with current behavior).

**Comment by languitar** [comment] 2017-12-21 13:32
For my workflow I always have several windows open and of the cursor jumps back to a different one after closing the checking window, I actually have to do something to get it back to the window I was actually working in. So I'd appreciate a solution for that ;-)

**Comment by rhysd** [comment] 2017-12-21 22:06
ok, I'll change the behavior of quit action.

**Comment by rhysd** [comment] 2017-12-21 22:08
Please update to the latest and try out.

**Comment by languitar** [comment] 2017-12-22 11:24
Seems to work well. Thanks!
