### ISSUE TITLE
handle syntax/markup

### ISSUE THREAD

**Issue by DerWeh** [rhysd/vim-grammarous#51] opened 2017-11-05 20:28 UTC
I use the plug-in mainly for Latex, and it clashes quite a lot with latex `markup' syntax.

Is there a way to better handle it? Possible solutions coming to my mind are
- giving regular expressions what to ignore (very bothersome to configure)
- using vim's syntax groups to ignore things
- using external tools like `detex` (for Latex) as helper.

**Comment by rhysd** [comment] 2017-11-06 07:02
I'm closing this because of duplicate of #40. Please discuss about this in #40.

I guess 

> using vim's syntax groups to ignore things

is most interesting and may be good idea. `detex` is not available I think because we need sourcemap between latex code and syntax-removed plain text to locate the error's position.

**Closed by rhysd** 2017-11-06 07:02 UTC
