### ISSUE TITLE
The [grammarous] window cause airline's denite extension to crash

### ISSUE THREAD

**Issue by quinoa42** [rhysd/vim-grammarous#46] opened 2017-08-24 15:46 UTC
When writing #45 , I found that if the airline's denite extension is enabled, whenever the [grammarous] is closed before calling `denite`, airline will crash with the message output below when one candidate is opened and vim jumped to a position with grammar error.

## minimal init.nvim:
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'rhysd/vim-grammarous' " with the denite source
call plug#end()

let g:python3_host_prog = $HOME . "/.pyenv/versions/neovim3/bin/python"
```

## way to produce
start neovim with the minimal init.nvim, type the following text in insert mode:
```
This is a error
```
then call `:GrammarousCheck`, one error should be detected at the `a` position. Move the cursor away from `a` and close the `[grammarous]` window manually. Then call `:Denite grammarous`, ~~which is added in the PR #45  so maybe you can use my fork [here](https://github.com/quinoa42/vim-grammarous).~~ (It's just merged). At now the Denite window should be opened while the `[grammarous]` window is closed. Now open the `a` candidate in denite, airline will crash with the message below.

```
"[Grammarous]"  19 lines --5%--
Error detected while processing function airline#extensions#denite#check_denite_mode[1]..denite#get_status_mode:
line    1:
E121: Undefined variable: b:denite_statusline_mode
Error detected while processing function airline#extensions#denite#check_denite_mode[1]..denite#get_status_mode:
line    1:
E15: Invalid expression: b:denite_statusline_mode
Error detected while processing function airline#extensions#denite#check_denite_mode:
line    2:
E684: list index out of range: 1
Error detected while processing function airline#extensions#denite#check_denite_mode:
line    2:
E116: Invalid arguments for function tolower(l:mode[1])
Error detected while processing function airline#extensions#denite#check_denite_mode:
line    2:
E15: Invalid expression: tolower(l:mode[1])
Error detected while processing function airline#extensions#denite#check_denite_mode[4]..airline#highlighter#highlight:
line    6:
E691: Can only compare List with List
Error detected while processing function airline#extensions#denite#check_denite_mode[4]..airline#highlighter#highlight:
line    6:
E15: Invalid expression: a:modes[0] == 'inactive' ? '_inactive' : ''
Error detected while processing function airline#extensions#denite#check_denite_mode[4]..airline#highlighter#highlight:
line    8:
E691: Can only compare List with List
Error detected while processing function airline#extensions#denite#check_denite_mode[4]..airline#highlighter#highlight:
line    8:
E15: Invalid expression: mode == 'inactive' && winnr('$') == 1
Error detected while processing function airline#extensions#denite#check_denite_mode[4]..airline#highlighter#highlight:
line   13:
E730: using List as a String
Error detected while processing function denite#get_status_sources:
line    1:
E121: Undefined variable: b:denite_statusline_sources
Error detected while processing function denite#get_status_sources:
line    1:
E15: Invalid expression: b:denite_statusline_sources
Error detected while processing function denite#get_status_path:
line    1:
E121: Undefined variable: b:denite_statusline_path
Error detected while processing function denite#get_status_path:
line    1:
E15: Invalid expression: b:denite_statusline_path
Error detected while processing function denite#get_status_linenr:
line    1:
E121: Undefined variable: b:denite_statusline_linenr
Error detected while processing function denite#get_status_linenr:
line    1:
E15: Invalid expression: b:denite_statusline_linenr
Error detected while processing function airline#extensions#denite#check_denite_mode[1]..denite#get_status_mode:
line    1:
E121: Undefined variable: b:denite_statusline_mode
Error detected while processing function airline#extensions#denite#check_denite_mode[1]..denite#get_status_mode:
line    1:
E15: Invalid expression: b:denite_statusline_mode
Error detected while processing function airline#extensions#denite#check_denite_mode:
line    2:
E684: list index out of range: 1
Error detected while processing function airline#extensions#denite#check_denite_mode:
line    2:
E116: Invalid arguments for function tolower(l:mode[1])
Error detected while processing function airline#extensions#denite#check_denite_mode:
...
...
```

This is easy to reproduce in my environment with the denite source I PRed. And when I disable airline, nothing will crash.

I'm not very familar with vim's feature and vimscript, but I guess it's because the denite window is kept by [grammarous], thus make airline confused. For reference, unite will not cause such a crash because unite's window is at the top while denite's is at the bottom.

In addition, when the [grammarous] window is open, nothing will crash either.

**Comment by rhysd** [comment] 2017-08-24 16:14
Hmm... This issue is related to 3 plugins; vim-grammarous, denite.vim and vim-airline. I want to clarify which plugin causes this.

At first glance at the error log, it seems that this is a mismatch between denite.vim and vim-airline. Are both the latest?

CC: @Shougo

**Comment by quinoa42** [comment] 2017-08-25 00:32
Yes, all the plugins have been updated to the latest before I tested.

**Comment by Shougo** [comment] 2017-08-25 01:35
@quinoa42 Please upload the reproduce ways from Vim starting.

> When writing #45 , I found that if the airline's denite extension is enabled, whenever the [grammarous] is closed before calling denite, airline will crash with the message output below when one candidate is opened and vim jumped to a position with grammar error:

This is hard to reproduce for me.  I don't know about vim-grammarous.

**Comment by Shougo** [comment] 2017-08-25 01:42
https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/denite.vim#L39

```
  " airline#extensions#denite#apply normally gets called only after the
  " denite window gets closed, so we have to call airline#update_statusline
  " ourselves to make sure it's applied when the window is opened.
```

?

**Comment by rhysd** [comment] 2017-08-25 01:58
denite.vim integration was merged at #45. Usage is [in README](https://github.com/rhysd/vim-grammarous#grammarous-denitenvim-source).

Although I'm not sure how to repro, the usage is following:

1. Open some text which contains a grammatical error (i.e. `This is a a text.`)
2. Execute `:GrammarousCheck`
3. Execute `:Denite grammarous`

**Comment by quinoa42** [comment] 2017-08-25 02:00
@Shougo @rhysd I just updated the detailed way to reproduce. Thanks for quick response.

**Comment by Shougo** [comment] 2017-08-25 02:02
OK.  It is reproduced.

**Comment by Shougo** [comment] 2017-08-25 02:03
It seems vim-airline error.  I cannot fix it.

**Comment by Shougo** [comment] 2017-08-25 02:07
`airline#extensions#denite#check_denite_mode()` is called empty filetype buffer.
I don't know why though.
It should check buffer `filetype` like this.

```vim
function! airline#extensions#denite#check_denite_mode(bufnr)
  if &filetype != 'denite'
    return ''
  endif
  let l:mode = split(denite#get_status_mode(), ' ')
  let l:mode = tolower(l:mode[1])
  if !exists('b:denite_mode_cache') || l:mode != b:denite_mode_cache
    call airline#highlighter#highlight([l:mode], a:bufnr)
    let b:denite_mode_cache = l:mode
  endif
  return ''
endfunction
```

**Comment by Shougo** [comment] 2017-08-25 02:08
@quinoa42 You should create the issue for vim-airline.

**Comment by Shougo** [comment] 2017-08-25 07:04
It is fixed in vim-airline.

**Comment by rhysd** [comment] 2017-08-25 07:10
@Shougo Thank you for your effort. @quinoa42, could you check that this issue was fixed?

**Comment by quinoa42** [comment] 2017-08-25 07:45
After the fixing I got other [errors](https://github.com/vim-airline/vim-airline/issues/1540#issuecomment-324847348), looks like the filetype is `denite` somehow. Is this due to async features?

**Comment by Shougo** [comment] 2017-08-25 08:25
> looks like the filetype is denite somehow. 

No.  It is empty filetype.

>  Is this due to async features?

No.  vim-airline calls denite functions in non denite buffer.
I don't know why.

**Comment by quinoa42** [comment] 2017-08-25 08:45
> No. It is empty filetype.
But if my understanding is correct, based on the code [here](https://github.com/vim-airline/vim-airline/commit/5345c8fafa0821453b86018d0472b124c068494f#diff-9948f8cbde21f2034a2ff3b8ccee31deR14) , if the filetype is empty then the called function should stop with the returned value '' right?

**Comment by Shougo** [comment] 2017-08-25 08:48
`airline#extensions#denite#check_denite_mode()` is stopped well.

But `denite#get_status_sources()` call is exists.
https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/denite.vim#L30

**Comment by quinoa42** [comment] 2017-08-25 12:13
@Shougo But in the call to `function! airline#extensions#denite#apply(...)`, filetype is also tested before calling denite's functions. I have no idea why this happens.

@rhysd Is it possible to add a switch that can disable all the invocations of `[grammarous]` window completely? I guess it can prevent that strange error. If the error does disappear, maybe I could try to implement the actions such as fix in the denite integration.

**Comment by rhysd** [comment] 2017-08-25 16:41
> Is it possible to add a switch that can disable all the invocations of [grammarous] window completely?

What does 'all the invocations of `[grammarous]` window' mean? Anyway, I don't think it's good idea to add a workaround before its root cause is revealed. I don't want to add additional complexity only for combination of specific plugins unless it's the only way to solve the problem

**Comment by Shougo** [comment] 2017-08-27 08:07
I have fixed the errors in denite.nvim.
Please update.

**Comment by quinoa42** [comment] 2017-08-31 07:20
@rhysd Okay, nevermind.
@Shougo
Sorry I was travelling these days. I just tested under the newest version and found that no blocking error happened. Although if the text are typed in the `no name` buffer without saving, one non-blocking error would happen:
```
[denite] function denite#helper#call_denite[15]..denite#start[4]..<SNR>136_start[30].._denite_start[1]..denite#util#execute_path, line 11
[denite] Vim(edit):E37: No write since last change (add ! to override)
```
Otherwise everything works fine. I'll close this issue.

**Closed** 2017-08-31 07:21 UTC

**Comment by Shougo** [comment] 2017-08-31 07:26
>  Although if the text are typed in the no name buffer without saving, one non-blocking warning would be produced:

This is Vim/neovim feature.
I think you have used `-split=no`.
